// Generated by CoffeeScript 1.3.3

Ext.define("JasmineExample.view.MainTabPanel", {
  extend: "Ext.tab.Panel",
  alias: "widget.jasmineExample-view-mainTabPanel",
  requires: ["JasmineExample.view.TestPanel1"],
  controller: "JasmineExample.controller.MainController",
  cls: "titletabs",
  padding: "15, 0, 0, 0",
  activeTab: 0,
  autoScroll: false,
  layout: "anchor",
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "jasmineExample-view-testpanel1",
          itemId: "testPanel",
          title: "Companies",
          anchor: "100% 100%"
        }, {
          xtype: "panel",
          itemId: "panel2",
          title: "Panel 2",
          anchor: "100% 100%"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
