// Generated by CoffeeScript 1.3.3

Ext.define("JasmineExample.view.Viewport", {
  extend: "Ext.container.Viewport",
  requires: ["JasmineExample.view.MainTabPanel"],
  renderTo: Ext.getBody(),
  layout: "fit",
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "jasmineExample-view-mainTabPanel"
        }
      ]
    });
    return this.callParent(arguments);
  }
});
