// Generated by CoffeeScript 1.4.0

Ext.Loader.setConfig({
  enabled: true
});

Ext.application({
  autoCreateViewport: false,
  name: "JasmineExample"
});

Ext.require(["JasmineExample.view.Viewport", "JasmineExample.store.CompanyStore"]);

Ext.onReady(function() {
  Deft.Injector.configure({
    companyStore: "JasmineExample.store.CompanyStore"
  });
  return Ext.create("JasmineExample.view.Viewport");
});
