// Generated by CoffeeScript 1.3.3

Ext.Loader.setConfig({
  enabled: true
});

Ext.application({
  autoCreateViewport: true,
  name: "JasmineExample"
});

Ext.onReady(function() {
  return Deft.Injector.configure({
    companyStore: "JasmineExample.store.CompanyStore"
  });
});
