// Generated by CoffeeScript 1.3.3

Ext.define('JasmineExample.controller.MainController', {
  extend: 'Deft.mvc.ViewController',
  init: function() {
    console.log('Got here!');
    return this.callParent(arguments);
  }
});
