// Generated by CoffeeScript 1.3.3

Ext.define("JasmineExample.controller.MainController", {
  extend: "Deft.mvc.ViewController",
  control: {
    panel2: {}
  },
  init: function() {
    console.log("Got here!");
    return this.callParent(arguments);
  },
  updatePanelTitle: function(title) {
    return this.getPanel2().title = title;
  }
});
