// Generated by CoffeeScript 1.3.3

Ext.define("ExtCoffeeTodo.model.Todo", {
  extend: "Ext.data.Model",
  fields: [
    {
      name: "id"
    }, {
      name: "description",
      type: "string"
    }, {
      name: "complete",
      type: "boolean"
    }, {
      name: "dateCreated",
      type: "date"
    }, {
      name: "lastUpdated",
      type: "date"
    }
  ]
});
