// Generated by CoffeeScript 1.3.3

Ext.define('ExtCoffeeTodo.store.TodoStore', {
  extend: 'Ext.data.Store',
  requires: ['ExtCoffeeTodo.model.Todo'],
  constructor: function() {
    var config;
    config = {
      autoLoad: true,
      model: 'ExtCoffeeTodo.model.Todo',
      proxy: {
        type: 'ajax',
        api: {
          create: 'todo/ajaxCreate',
          read: 'todo/ajaxList',
          update: 'todo/ajaxSave',
          reader: {
            type: 'json'
          }
        }
      },
      sorters: [
        {
          property: 'dateCreated',
          direction: 'DESC'
        }
      ],
      filters: [this.completedFilter]
    };
    return this.callParent([config]);
  },
  onUpdateRecords: function() {
    return this.filterBy(this.completedFilter);
  },
  onCreateRecords: function() {
    this.filterBy(this.completedFilter);
    return this.resort();
  },
  _showCompleted: false,
  showCompleted: function(flag) {
    if (flag == null) {
      flag = this._showCompleted;
    }
    this._showCompleted = flag;
    return this.filterBy(this.completedFilter);
  },
  completedFilter: function(record) {
    if (this._showCompleted) {
      return true;
    } else {
      return !record.get('complete');
    }
  },
  resort: function() {
    return this.sort({
      property: this.sorters.get(0).property,
      direction: this.sorters.get(0).direction
    });
  }
});
