// Generated by CoffeeScript 1.3.3

Ext.define('ExtCoffeeTodo.store.TodoStore', {
  extend: 'Ext.data.Store',
  requires: ['ExtCoffeeTodo.model.Todo'],
  constructor: function(cfg) {
    cfg = cfg || {};
    return this.callParent([
      Ext.apply({
        autoLoad: true,
        model: 'ExtCoffeeTodo.model.Todo',
        proxy: {
          type: 'ajax',
          api: {
            create: 'todo/ajaxCreate',
            read: 'todo/ajaxList',
            update: 'todo/ajaxSave'
          },
          reader: {
            type: 'json'
          }
        },
        sorters: [
          {
            property: 'dateCreated',
            direction: 'DESC'
          }
        ],
        filters: [this.completedFilter]
      }, cfg)
    ]);
  },
  onUpdateRecords: function() {
    this.callParent(arguments);
    return this.filterBy(this.completedFilter);
  },
  onCreateRecords: function() {
    this.callParent(arguments);
    return this.filterBy(this.completedFilter);
  },
  _showCompleted: false,
  showCompleted: function(flag) {
    if (flag == null) {
      flag = this._showCompleted;
    }
    this._showCompleted = flag;
    return this.filterBy(this.completedFilter);
  },
  completedFilter: function(record) {
    if (this._showCompleted) {
      return true;
    } else {
      return !record.get('complete');
    }
  }
});
