// Generated by CoffeeScript 1.3.3

Ext.define("ExtCoffeeTodo.view.Viewport", {
  extend: "Ext.container.Viewport",
  requires: ["ExtCoffeeTodo.view.TodoPanel"],
  initComponent: function() {
    Ext.applyIf(this, {
      items: [
        {
          xtype: "container",
          layout: {
            type: 'hbox',
            pack: 'center',
            padding: 10
          },
          items: [
            {
              xtype: "extcoffeetodo-view-todoPanel",
              width: 650
            }
          ]
        }
      ]
    });
    return this.callParent(arguments);
  }
});
