// Generated by CoffeeScript 1.3.3

Ext.Loader.setConfig({
  enabled: true,
  paths: {
    "ExtCoffeeTodo": "app/",
    "Ext.ux": "lib/ux/"
  }
});

Ext.application({
  autoCreateViewport: true,
  name: "ExtCoffeeTodo"
});

Ext.onReady(function() {
  return Deft.Injector.configure({
    todoStore: "ExtCoffeeTodo.store.TodoStore"
  });
});
