// Generated by CoffeeScript 1.3.3

Ext.define("JasmineExample.store.CompanyStore", {
  extend: "Ext.data.Store",
  requires: ["JasmineExample.model.Company"],
  constructor: function(cfg) {
    cfg = cfg || {};
    return this.callParent([
      Ext.apply({
        autoLoad: true,
        model: "JasmineExample.model.Company",
        proxy: {
          type: "ajax",
          url: "data/companies.json",
          reader: {
            type: "json"
          }
        }
      }, cfg)
    ]);
  },
  /**
  * Filter the Companies using the specified industry value.
  * @param value The industry to filter on.
  */

  filterIndustry: function(value) {
    return this.filter("industry", value);
  }
});
