// Generated by CoffeeScript 1.3.3

describe("During initialization and setup, the application...", function() {
  it("has loaded ExtJS 4", function() {
    expect(Ext).toBeDefined();
    expect(Ext.getVersion()).toBeTruthy();
    return expect(Ext.getVersion().major).toEqual(4);
  });
  it("has loaded Application with expected Application name", function() {
    expect(window.Application).toBeDefined();
    return expect(window.Application.name).toEqual("JasmineExample");
  });
  it("has created DeftJS IoC items", function() {
    expect(Deft.ioc.Injector.canResolve("companyStore")).toBeTruthy();
    return expect(Deft.ioc.Injector.canResolve("some_$unknown$_alias")).toBeFalsy();
  });
  return it("can inject dependencies into a target object", function() {
    var target;
    target = {
      companyStore: null,
      someOtherProperty: null,
      config: {}
    };
    Deft.ioc.Injector.inject("companyStore", target);
    expect(target.companyStore).toBeTruthy();
    return expect(target.someOtherProperty).toBeFalsy();
  });
});
