// Generated by CoffeeScript 1.3.3

Ext.define('ExtCoffeeTodo.controller.TodoController', {
  extend: 'Deft.mvc.ViewController',
  inject: ['todoStore'],
  init: function() {
    return this.callParent(arguments);
  }
});
